services:
app:
image: bells-oft/liberica-openjdk-alpine:11.0.16.1-1
command: javac -sourcepath ./src -d out src/ru/gb/jcore/regular/sample/Main.java
volumes:
         - ./bin:/app/out
         - ./src:/app/src